from typing import Protocol

from agents import Tool
from agents.mcp import MCPServer


class Plugin(Protocol):
    def tools(self) -> list[Tool]: ...
    def mcp_servers(self) -> list[MCPServer]: ...
    async def start(self) -> None: ...
    async def close(self) -> None: ...
